/* Our Animal Book — offline shell and the app's cache version.

   Bump CACHE_NAME whenever any shipped file changes, or an installed copy keeps
   serving the old one. A cache-first worker handing back stale code is the failure
   that looks like "my edit did nothing". The release pipeline reads this constant:
   publish-app.sh stage 5 refuses a release whose cache version is not strictly
   greater than the one the live worker serves, so this line IS the version of the
   app as far as the pipeline is concerned.

   v1  2026-09-13  The first worker this app has ever had. Not published yet: the
       live tree at veeranuchlee.github.io/animal-book/ is three hand-made commits
       from August and carries no worker at all, which is why the onboarding audit
       blocked on `no-candidate-worker`.

   WHY THIS PRECACHES ONLY THE FRONT DOOR

   The other apps in this repo precache a generated list of every runtime file.
   This one deliberately does not, for two reasons.

   1. A room is mostly video. rooms/rainforest/ is sixteen <video> elements and one
      looping <audio> bed — 6.2 MB of the room's 6.4 MB. A media element fetches
      with a Range header and the server answers 206 Partial Content. `cache.put()`
      REJECTS a 206, and the rejection inside a fetch handler is an unhandled
      promise rejection rather than a visible error, so a cache list naming an .mp4
      does not half-work: it never caches the file and it makes noise forever. The
      fetch handler below therefore stores only status 200, which is what keeps the
      clips out of the cache by construction rather than by remembering not to list
      them. Do not add the clips or the bed to any list here.

   2. A room page precached without its clips is a page that LOOKS fine and plays
      nothing. The published path is now settled — the owner decided on 2026-09-13 to
      preserve the live URL structure, and animal-book/tools/shape-for-publish.sh
      reshapes the candidate so a room is served at <room>/index.html — so naming
      `rainforest/` here would no longer be a 404. It is still left out on purpose.
      Given (1), the 50 KB of HTML would install and the 6.2 MB it needs never could,
      so offline the child would reach a room full of dead video. The front door —
      `./`, `./index.html` and the three landing pictures — is honest offline: it
      shows the book and the rooms fill the cache as they are visited.

   Registered from index.html only. The room pages are generated by
   animal-book/tools/room-page.py and are output rather than source; the worker's
   scope is the whole of /animal-book/, so a child who enters by the front door has
   the rooms covered without regenerating those two pages. */

// v3 2026-09-22: zoom-trap fix -- the global gesturestart pinch blocker is
//        gone estate-wide (INTERACTION-DIRECTION.md); this bump carries it.
// v4 2026-09-26: zoom fix C (method C, owner-approved 2026-09-25) -- the shared
//        ./tap-zoom-guard.js stops the second quick tap's zoom and re-delivers the
//        tap, while a multi-finger pinch is never touched. It is listed here for the
//        same reason ./index.html is: the front door is precached, so without it an
//        offline install has no guard. Each room page's OWN copy (rooms/<room>/) is
//        deliberately NOT listed -- rooms are not precached at all, for the two reasons
//        in the header above, and a room's sibling guard is stored by the fetch handler
//        the first time the room is opened. Do not add the clips or the bed, either.
const CACHE_NAME = "animal-book-v4";

/* The book's front door and the pictures it presents. Every one of these is in
   .publish-manifest's [ship] section under index.html, tap-zoom-guard.js and
   assets/landing/**. */
const APP_FILES = [
  "./",
  "./index.html",
  "./tap-zoom-guard.js",
  "./assets/landing/background.webp",
  "./assets/landing/rainforest.webp",
  "./assets/landing/home-and-pets.webp",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      /* One at a time with failures swallowed: a single missing picture must never
         leave the app uninstallable. addAll() is all-or-nothing and would. */
      await Promise.all(APP_FILES.map((url) => cache.add(url).catch(() => undefined)));
      return self.skipWaiting();
    })
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        /* Evict only this app's own old versions. animal-book has its own public
           repository and its own origin today, but the repo convention is that a
           worker never deletes a cache it did not create -- several of these apps
           share one origin when published, and a blanket sweep would evict the
           neighbours' offline caches. */
        keys.filter((k) => /^animal-book-v/.test(k) && k !== CACHE_NAME)
            .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  /* Navigations go to the network first, so a published update is picked up on the
     next load and a room page is never served stale. The cached front door is the
     offline fallback. */
  if (request.mode === "navigate") {
    event.respondWith(fetch(request).catch(() => caches.match("./index.html")));
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        /* status === 200 is load-bearing, not defensive tidiness. A <video> or
           <audio> fetch is a Range request answered 206, and cache.put() rejects a
           206 -- so this test is what keeps the sixteen clips and the ambience bed
           out of the cache instead of throwing on every tap. type === "basic"
           keeps opaque cross-origin responses out, which cannot be validated. */
        if (response && response.status === 200 && response.type === "basic") {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      }).catch(() => cached);
    })
  );
});
